"""
Constants for the Data Processor application.
"""

# File processing constants
MAX_FILE_SIZE_MB = 500
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024  # Convert MB to bytes
CHUNK_SIZE = 10000
DEFAULT_ENCODING = 'utf-8'

# UI constants
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800
DEFAULT_PADDING = 10
DEFAULT_BUTTON_HEIGHT = 30
DEFAULT_TEXT_HEIGHT = 20
DEFAULT_SEARCH_WIDTH = 200
GRID_WEIGHT_MAIN = 1
FONT_SIZE = 12

# Processing constants
DEFAULT_SAMPLE_RATE = 1000
MAX_PLOT_POINTS = 10000
MIN_SIGNAL_DATA_POINTS = 10
MIN_PERIODS_DEFAULT = 2
LARGE_SIGNAL_THRESHOLD = 1000
SIGNAL_BATCH_SIZE = 100
BULK_SAMPLE_SIZE = 1000
LARGE_FILE_THRESHOLD = 10000
LARGE_BATCH_SIZE = 1000
SMALL_BATCH_SIZE = 100

# Timing constants
PLOT_UPDATE_DELAY_MS = 100
UI_UPDATE_DELAY_MS = 50
LAYOUT_SAVE_DELAY_MS = 500
MILLISECONDS_PER_SECOND = 1000
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600

# Export constants
DEFAULT_DPI = 300
SUPPORTED_FORMATS = ['.csv', '.xlsx', '.json', '.parquet']
EXCEL_SHEET_NAME_MAX_LENGTH = 31

# Logging constants
LOG_LEVEL = 'INFO'
MAX_LOG_SIZE = 10 * 1024 * 1024  # 10MB

# Filter Engine Constants
DEFAULT_BW_CUTOFF = 0.1
DEFAULT_BW_ORDER = 4
DEFAULT_BW_NYQUIST = 0.5
MIN_BUTTERWORTH_DATA_MULTIPLIER = 3
DEFAULT_MA_WINDOW = 5
DEFAULT_MEDIAN_KERNEL = 5
MIN_KERNEL_SIZE = 3
DEFAULT_SAVGOL_WINDOW = 5
DEFAULT_SAVGOL_POLYORDER = 3
MAX_DERIVATIVE_ORDER = 3
DEFAULT_HAMPEL_WINDOW = 5
DEFAULT_HAMPEL_THRESHOLD = 3.0
DEFAULT_ZSCORE_THRESHOLD = 3.0
DEFAULT_ZSCORE_METHOD = 'modified'
NORMAL_DISTRIBUTION_CONSTANT = 0.6745
DEFAULT_GAUSSIAN_SIGMA = 1.0
DEFAULT_GAUSSIAN_MODE = 'reflect'

# FFT Filter Constants
DEFAULT_FFT_FREQ_HIGH = 100.0
DEFAULT_FFT_FREQ_LOW = 0.1
DEFAULT_FFT_FREQ_UNIT = 'Hz'
DEFAULT_FFT_TRANSITION_BW = 0.1
DEFAULT_FFT_WINDOW_SHAPE = 'hann'
DEFAULT_FFT_ZERO_PHASE = True
MAX_FFT_FREQUENCY = 1000.0
MAX_FFT_TRANSITION_BW = 100.0
MIN_FFT_FREQUENCY = 0.001
MIN_FFT_TRANSITION_BW = 0.001

# Plot constants
ZOOM_OUT_FACTOR = 0.8
ZOOM_IN_FACTOR = 1.2
DEFAULT_LINE_WIDTH = 1.0
DEFAULT_GRID_ALPHA = 0.3
DEFAULT_GRID_LINESTYLE = '--'
DEFAULT_ALPHA = 1.0

# Time column detection
TIME_COLUMN_KEYWORDS = ['time', 'timestamp', 'date', 'datetime', 't']

# Default plot settings
DEFAULT_PLOT_TITLE = 'Data Plot'
DEFAULT_PLOT_XLABEL = 'Time'
DEFAULT_PLOT_YLABEL = 'Value'
DEFAULT_LEGEND_POSITION = 'upper right'
DEFAULT_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DEFAULT_START_TIME = '00:00:00'
DEFAULT_END_TIME = '23:59:59'

# Error messages
ERROR_MSG_NO_FILES = 'No files selected'
ERROR_MSG_EMPTY_FILE = 'File is empty'
ERROR_MSG_NO_PLOTS = 'No plots to display'
