"""Camera-agnostic markerless-mocap contracts and deterministic interchange."""

from .acquisition import (
    AcquisitionError,
    CaptureGroup,
    DropPolicy,
    FramePacket,
    FrameSource,
    PrerecordedFrameSource,
    QueueFullError,
    SourceState,
    SyntheticFrameSource,
)
from .adapters import (
    ApprovalStatus,
    ExternalServicePoseAdapter,
    KeypointMapping,
    LicenseCategory,
    LicenseEvaluationResult,
    LicenseRecord,
    MediaPipePoseAdapter,
    PermittedUse,
    PoseBackendProtocol,
    PoseInferenceResult,
    PoseInferenceStatus,
    ProviderLicenseManifest,
    SkeletonConverter,
    SyntheticPoseAdapter,
    get_canonical_skeleton,
    get_default_mediapipe_mapping,
)
from .calibration import (
    CalibrationDegeneracyKind,
    CalibrationObservation,
    CalibrationPatternKind,
    CalibrationQuality,
    CalibrationTarget,
    DistortionCoefficients,
    DistortionModel,
    FisheyeIntrinsics,
    IntrinsicCalibrationResult,
    PinholeIntrinsics,
    ReprojectionResidual,
    check_coverage_and_degeneracy,
    evaluate_intrinsic_quality,
)
from .devices import CameraCapabilities, CameraIdentity, FeatureSupport, NumericRange
from .enums import Availability, ClockKind, SessionState, ShutterKind, SupportLevel
from .extrinsics import (
    CameraLayout,
    CameraPose,
    ExtrinsicCalibrationResult,
    ExtrinsicDegeneracyKind,
    ExtrinsicQuality,
    MovementDetectionResult,
    RelocalizationResult,
    bundle_adjust_layout,
    detect_camera_movement,
    estimate_pnp_pose,
    evaluate_extrinsic_quality,
)
from .geometry import CoordinateFrame, RigidTransform
from .observations import Landmark3D, PixelObservation, SkeletonDefinition
from .recording import (
    FrameIndexEntry,
    RecordingIntegrityReport,
    RecordingReader,
    RecordingWriter,
)
from .serialization import dumps_canonical, load_session_manifest
from .session import (
    MOCAP_SESSION_SCHEMA_VERSION,
    MethodDescriptor,
    MocapSessionManifest,
    RecordingPolicy,
)
from .sync import (
    ClockSkewEstimate,
    SyncAnomaly,
    SyncAnomalyType,
    SyncMonitor,
    SyncQuality,
)
from .timebase import ClockDomain, FrameStamp

__all__ = [
    "MOCAP_SESSION_SCHEMA_VERSION",
    "AcquisitionError",
    "ApprovalStatus",
    "Availability",
    "CalibrationDegeneracyKind",
    "CalibrationObservation",
    "CalibrationPatternKind",
    "CalibrationQuality",
    "CalibrationTarget",
    "CameraCapabilities",
    "CameraIdentity",
    "CameraLayout",
    "CameraPose",
    "CaptureGroup",
    "ClockDomain",
    "ClockKind",
    "ClockSkewEstimate",
    "CoordinateFrame",
    "DistortionCoefficients",
    "DistortionModel",
    "DropPolicy",
    "ExternalServicePoseAdapter",
    "ExtrinsicCalibrationResult",
    "ExtrinsicDegeneracyKind",
    "ExtrinsicQuality",
    "FeatureSupport",
    "FisheyeIntrinsics",
    "FrameIndexEntry",
    "FramePacket",
    "FrameSource",
    "FrameStamp",
    "IntrinsicCalibrationResult",
    "KeypointMapping",
    "Landmark3D",
    "LicenseCategory",
    "LicenseEvaluationResult",
    "LicenseRecord",
    "MediaPipePoseAdapter",
    "MethodDescriptor",
    "MocapSessionManifest",
    "MovementDetectionResult",
    "NumericRange",
    "PermittedUse",
    "PinholeIntrinsics",
    "PixelObservation",
    "PoseBackendProtocol",
    "PoseInferenceResult",
    "PoseInferenceStatus",
    "PrerecordedFrameSource",
    "ProviderLicenseManifest",
    "QueueFullError",
    "RecordingIntegrityReport",
    "RecordingPolicy",
    "RecordingReader",
    "RecordingWriter",
    "RelocalizationResult",
    "ReprojectionResidual",
    "RigidTransform",
    "SessionState",
    "ShutterKind",
    "SkeletonConverter",
    "SkeletonDefinition",
    "SourceState",
    "SupportLevel",
    "SyncAnomaly",
    "SyncAnomalyType",
    "SyncMonitor",
    "SyncQuality",
    "SyntheticFrameSource",
    "SyntheticPoseAdapter",
    "bundle_adjust_layout",
    "check_coverage_and_degeneracy",
    "detect_camera_movement",
    "dumps_canonical",
    "estimate_pnp_pose",
    "evaluate_extrinsic_quality",
    "evaluate_intrinsic_quality",
    "get_canonical_skeleton",
    "get_default_mediapipe_mapping",
    "load_session_manifest",
]
