self-hosted-runner:
  labels:
    - d-sorg-fleet
    - d-sorg-fleet-2core
    - d-sorg-fleet-14core
    - d-sorg-fleet-fast-io
    - ubuntu-latest
    - ubuntu-22.04
    - ubuntu-24.04
    - d-sorg-windows-security
