repos:
# Python formatters
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks: 
    - id: black
      language_version: python3.11

- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks: 
    - id: isort
      args: ["--profile", "black"]

# Python linter
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks: 
    - id: ruff
      args: ["--fix", "--select", "ALL", "--ignore", "D,ANN101,ANN102"]

# Type checker
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
    - id: mypy
      additional_dependencies: ["types-requests", "types-PyYAML"]
      args: ["--strict", "--ignore-missing-imports"]

# Jupyter notebook cleaner
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks: 
    - id: nbstripout

# Local quality checks
- repo: local
  hooks:
    # Main quality gate
    - id: quality-check
      name: Quality check (no placeholders/magic numbers)
      entry: python scripts/quality-check.py
      language: python
      pass_filenames: false
      always_run: true
      additional_dependencies: []
      
    # Block placeholders in Python
    - id: no-placeholders-python
      name: Check for TODO/FIXME/placeholders in Python
      entry: bash -c '! grep -r "TODO\|FIXME\|XXX\|HACK\|BUG\|OPTIMIZE\|REFACTOR\|pass #\|pass$\|^\s*\.\.\.\s*$\|NotImplementedError" --include="*.py" --exclude-dir=".git" --exclude-dir="archive" --exclude-dir="legacy" .'
      language: system
      types: [python]
      
    # Block "approximately" in comments/code
    - id: no-approximations
      name: No "approximately" in technical code
      entry: bash -c '! grep -ri "approximately\|approx\s\|roughly\|about\s[0-9]\|around\s[0-9]\|close to\|near\|~[0-9]" --include="*.py" --include="*.m" --exclude-dir=".git" --exclude-dir="docs" .'
      language: system
      pass_filenames: false
      
    # Check for magic numbers in Python
    - id: no-magic-numbers
      name: Check for magic numbers
      entry: bash -c '! grep -r "\b[^a-zA-Z_]3\.14[0-9]*\|9\.8[0-9]*\|2\.71[0-9]*\|6\.67[0-9]*\|1\.61[0-9]*\b" --include="*.py" --exclude-dir=".git" --exclude-dir="tests" . || echo "Warning: Possible magic numbers (should be named constants)"'
      language: system
      types: [python]
      
    # Ensure tests exist for new Python modules
    - id: tests-exist
      name: Check tests exist for Python modules
      entry: bash -c 'for f in $(find python -name "*.py" -not -path "*/test*" -not -name "__*" 2>/dev/null); do base=$(basename $f .py); if ! find . -path "*/test*" -name "*${base}*" | grep -q .; then echo "Warning: No test found for $f"; fi; done; true'
      language: system
      pass_filenames: false
      
    # Check for print statements in libraries
    - id: no-print-in-libs
      name: No print statements in library code
      entry: bash -c '! grep -r "print(" --include="*.py" --exclude-dir="scripts" --exclude-dir="tests" --exclude-dir=".git" python/'
      language: system
      pass_filenames: false

# Global settings
default_language_version:
  python: python3.11

# Files to always exclude
exclude: '^(archive/|legacy/|experimental/|\.git/)'