"""Shared variation / Monte-Carlo engine (epic #4120, phase V3).

One 'how parameters vary' vocabulary for the whole repo: a namespaced
variable registry (:mod:`.spec`), a seeded parallel N-run executor
(:mod:`.engine`), dispersion/sensitivity analysis (:mod:`.analysis`),
and CSV/JSON dataset IO (:mod:`.dataset_io`).

Deliberately NOT re-exported from ``shared.python.swing_sim`` — import
from this subpackage directly (same policy as ``swing_sim.solver``).
"""

from __future__ import annotations

from .analysis import (
    DispersionEllipse,
    OutputStats,
    SensitivityResult,
    dispersion_ellipse,
    one_at_a_time_sensitivity,
    spearman_matrix,
    summary_stats,
)
from .engine import (
    DELIVERY_OUTPUTS,
    FLIGHT_OUTPUTS,
    LAUNCH_OUTPUTS,
    CancelledError,
    ProgressReport,
    VariationDataset,
    evaluate_run,
    outputs_for_mode,
    run_variation,
    sample_inputs,
)
from .ensemble_geometry import (
    EnsemblePositionTraces,
    LowVariabilityCriteria,
    LowVariabilityInterval,
    PositionDispersion,
    compute_position_dispersion,
    compute_position_dispersion_view,
    find_low_variability_intervals,
)
from .global_sensitivity import (
    MORRIS_REPORT_SCHEMA_ID,
    MORRIS_REPORT_SCHEMA_VERSION,
    MorrisEstimate,
    MorrisReport,
    analyze_morris,
)
from .group_spec import PerturbationGroup
from .morris_design import (
    MorrisDesign,
    MorrisFactor,
    MorrisObservations,
    MorrisOutput,
    generate_morris_design,
)
from .morris_execution import (
    MAX_MORRIS_OBSERVATION_CELLS,
    MAX_MORRIS_SAMPLES,
    MAX_MORRIS_WORKERS,
    MORRIS_PROGRESS_INTERVAL,
    MorrisEvaluation,
    MorrisEvaluator,
    MorrisExecutionOptions,
    MorrisSample,
    evaluate_morris_design,
)
from .morris_observation_io import (
    MORRIS_OBSERVATION_SCHEMA_ID,
    MORRIS_OBSERVATION_SCHEMA_VERSION,
    MorrisObservationArchive,
    make_morris_observation_archive,
    morris_design_sha256,
    morris_observations_from_json_dict,
    morris_observations_to_json_dict,
)
from .propagation import (
    CommonReferenceTrace,
    PairedIntervention,
    PropagationResult,
    analyze_paired_intervention,
)
from .spec import (
    CATEGORY_BALL_SETUP,
    CATEGORY_CLUB,
    CATEGORY_DELIVERY,
    CATEGORY_LAUNCH,
    CATEGORY_SWING,
    DISTRIBUTIONS,
    MODE_CATEGORIES,
    MODES,
    SCHEMA_VERSION,
    SWING_DERIVED_KEYS,
    NoiseSpec,
    VariableDef,
    VariationPlan,
    keys_for_mode,
    register_variable,
    variable_registry,
    variables_in_category,
)

__all__ = [
    "CATEGORY_BALL_SETUP",
    "CATEGORY_CLUB",
    "CATEGORY_DELIVERY",
    "CATEGORY_LAUNCH",
    "CATEGORY_SWING",
    "DELIVERY_OUTPUTS",
    "DISTRIBUTIONS",
    "FLIGHT_OUTPUTS",
    "LAUNCH_OUTPUTS",
    "MODES",
    "MODE_CATEGORIES",
    "SCHEMA_VERSION",
    "SWING_DERIVED_KEYS",
    "CancelledError",
    "CommonReferenceTrace",
    "DispersionEllipse",
    "EnsemblePositionTraces",
    "LowVariabilityCriteria",
    "LowVariabilityInterval",
    "MorrisDesign",
    "MorrisEstimate",
    "MorrisEvaluation",
    "MorrisObservationArchive",
    "make_morris_observation_archive",
    "morris_design_sha256",
    "MorrisEvaluator",
    "MorrisExecutionOptions",
    "MorrisFactor",
    "MorrisObservations",
    "MorrisOutput",
    "MorrisReport",
    "MorrisSample",
    "MAX_MORRIS_OBSERVATION_CELLS",
    "MAX_MORRIS_SAMPLES",
    "MAX_MORRIS_WORKERS",
    "MORRIS_PROGRESS_INTERVAL",
    "MORRIS_OBSERVATION_SCHEMA_ID",
    "MORRIS_OBSERVATION_SCHEMA_VERSION",
    "MORRIS_REPORT_SCHEMA_ID",
    "MORRIS_REPORT_SCHEMA_VERSION",
    "NoiseSpec",
    "OutputStats",
    "PairedIntervention",
    "ProgressReport",
    "PropagationResult",
    "PositionDispersion",
    "PerturbationGroup",
    "SensitivityResult",
    "VariableDef",
    "VariationDataset",
    "VariationPlan",
    "dispersion_ellipse",
    "evaluate_morris_design",
    "analyze_morris",
    "morris_observations_from_json_dict",
    "morris_observations_to_json_dict",
    "analyze_paired_intervention",
    "compute_position_dispersion",
    "compute_position_dispersion_view",
    "evaluate_run",
    "keys_for_mode",
    "find_low_variability_intervals",
    "generate_morris_design",
    "one_at_a_time_sensitivity",
    "outputs_for_mode",
    "register_variable",
    "run_variation",
    "sample_inputs",
    "spearman_matrix",
    "summary_stats",
    "variable_registry",
    "variables_in_category",
]
