"""Shared variation / Monte-Carlo engine (epic #4120, phase V3).

One 'how parameters vary' vocabulary for the whole repo: a namespaced
variable registry (:mod:`.spec`), a seeded parallel N-run executor
(:mod:`.engine`), dispersion/sensitivity analysis (:mod:`.analysis`),
and CSV/JSON dataset IO (:mod:`.dataset_io`).

Deliberately NOT re-exported from ``shared.python.swing_sim`` — import
from this subpackage directly (same policy as ``swing_sim.solver``).
"""

from __future__ import annotations

from .analysis import (
    DispersionEllipse,
    OutputStats,
    SensitivityResult,
    dispersion_ellipse,
    finite_sample_standard_deviation,
    one_at_a_time_sensitivity,
    sensitivity_from_standard_deviations,
    spearman_matrix,
    summary_stats,
)
from .dataset_io import (
    DATASET_HDF5_SCHEMA_ID,
    DATASET_HDF5_SCHEMA_VERSION,
    DATASET_JSON_SCHEMA_VERSION,
    from_json_dict,
    read_csv,
    read_hdf5,
    read_json,
    to_json_dict,
    write_csv,
    write_hdf5,
    write_json,
)
from .dispersion_metric_types import (
    ELLIPSOID_VOLUME,
    ESTIMABLE,
    GAUSSIAN_POSITION_CONTENT_REGION,
    INSUFFICIENT_SAMPLES,
    INVALID_COVARIANCE,
    LARGEST_PRINCIPAL_SIGMA,
    LOW_VARIABILITY_METRICS,
    MIN_CONFIDENCE_LEVEL,
    MIN_SAMPLES_FOR_FULL_3D_COVARIANCE,
    RANK_DEFICIENT,
    RMS_RADIUS,
    ConfidenceEllipsoidSeries,
    DispersionMetricSeries,
    LowVariabilityMetricCriteria,
    RankedLowVariabilityInterval,
)
from .dispersion_metrics import (
    build_confidence_ellipsoids,
    build_dispersion_metric_series,
    find_ranked_low_variability_intervals,
)
from .engine import (
    DELIVERY_OUTPUTS,
    FLIGHT_OUTPUTS,
    LAUNCH_OUTPUTS,
    CancelledError,
    ProgressReport,
    VariationDataset,
    evaluate_run,
    outputs_for_mode,
    run_variation,
)
from .ensemble_geometry import (
    MAX_DISPERSION_ACCUMULATOR_BYTES,
    EnsemblePositionTraces,
    LowVariabilityCriteria,
    LowVariabilityInterval,
    PositionDispersion,
    PositionDispersionAccumulator,
    compute_position_dispersion,
    compute_position_dispersion_view,
    find_low_variability_intervals,
)
from .global_sensitivity import (
    MORRIS_REPORT_SCHEMA_ID,
    MORRIS_REPORT_SCHEMA_VERSION,
    MorrisEstimate,
    MorrisReport,
    analyze_morris,
)
from .group_spec import PerturbationGroup
from .morris_design import (
    MorrisDesign,
    MorrisFactor,
    MorrisObservations,
    MorrisOutput,
    generate_morris_design,
)
from .morris_execution import (
    MAX_MORRIS_OBSERVATION_CELLS,
    MAX_MORRIS_SAMPLES,
    MAX_MORRIS_WORKERS,
    MORRIS_PROGRESS_INTERVAL,
    MorrisEvaluation,
    MorrisEvaluator,
    MorrisExecutionOptions,
    MorrisSample,
    evaluate_morris_design,
)
from .morris_observation_io import (
    MORRIS_OBSERVATION_SCHEMA_ID,
    MORRIS_OBSERVATION_SCHEMA_VERSION,
    MorrisObservationArchive,
    make_morris_observation_archive,
    morris_design_sha256,
    morris_observations_from_json_dict,
    morris_observations_to_json_dict,
)
from .noise_response import (
    ADEQUACY_ESTIMABLE,
    ADEQUACY_INSUFFICIENT_PAIRS,
    ADEQUACY_UNSUPPORTED_BOUNDED,
    ADEQUACY_UNSUPPORTED_CORRELATED,
    ADEQUACY_UNSUPPORTED_DISCRETE,
    ADEQUACY_ZERO_PERTURBATION,
    POSITION_NOISE_RESPONSE_FIELD_SCHEMA_ID,
    POSITION_NOISE_RESPONSE_FIELD_SCHEMA_VERSION,
    PositionNoiseResponseField,
    ResponseAccumulatorSnapshot,
    ResponseFieldAccumulator,
    ResponseFieldInput,
    compute_position_noise_response_field,
    response_field_fingerprint,
)
from .noise_response_plot import (
    PositionNoiseResponsePlotRow,
    iter_position_noise_response_plot_rows,
)
from .propagation import (
    CommonReferenceTrace,
    PairedIntervention,
    PropagationResult,
    analyze_paired_intervention,
)
from .sampling import sample_input_block, sample_input_chunks, sample_inputs
from .spec import (
    CATEGORY_BALL_SETUP,
    CATEGORY_CLUB,
    CATEGORY_DELIVERY,
    CATEGORY_LAUNCH,
    CATEGORY_SWING,
    DISTRIBUTIONS,
    LOCALIZED_TORQUE_VARIABLE_JOINTS,
    MODE_CATEGORIES,
    MODES,
    SCHEMA_VERSION,
    SWING_DERIVED_KEYS,
    NoiseSpec,
    VariableDef,
    VariationPlan,
    keys_for_mode,
    register_variable,
    variable_registry,
    variables_in_category,
)
from .trace_resampling import (
    TRACE_RESAMPLING_POLICY_ID,
    TraceResamplingResult,
    resample_position_traces,
)

__all__ = [
    "CATEGORY_BALL_SETUP",
    "CATEGORY_CLUB",
    "CATEGORY_DELIVERY",
    "CATEGORY_LAUNCH",
    "CATEGORY_SWING",
    "DATASET_HDF5_SCHEMA_ID",
    "DATASET_HDF5_SCHEMA_VERSION",
    "DATASET_JSON_SCHEMA_VERSION",
    "DELIVERY_OUTPUTS",
    "DISTRIBUTIONS",
    "FLIGHT_OUTPUTS",
    "LAUNCH_OUTPUTS",
    "LOCALIZED_TORQUE_VARIABLE_JOINTS",
    "MAX_DISPERSION_ACCUMULATOR_BYTES",
    "MODES",
    "MODE_CATEGORIES",
    "SCHEMA_VERSION",
    "SWING_DERIVED_KEYS",
    "CancelledError",
    "CommonReferenceTrace",
    "DispersionEllipse",
    "EnsemblePositionTraces",
    "ELLIPSOID_VOLUME",
    "ESTIMABLE",
    "GAUSSIAN_POSITION_CONTENT_REGION",
    "LowVariabilityCriteria",
    "LowVariabilityInterval",
    "LowVariabilityMetricCriteria",
    "LARGEST_PRINCIPAL_SIGMA",
    "LOW_VARIABILITY_METRICS",
    "MIN_SAMPLES_FOR_FULL_3D_COVARIANCE",
    "MIN_CONFIDENCE_LEVEL",
    "INSUFFICIENT_SAMPLES",
    "INVALID_COVARIANCE",
    "MorrisDesign",
    "MorrisEstimate",
    "MorrisEvaluation",
    "MorrisObservationArchive",
    "make_morris_observation_archive",
    "morris_design_sha256",
    "MorrisEvaluator",
    "MorrisExecutionOptions",
    "MorrisFactor",
    "MorrisObservations",
    "MorrisOutput",
    "MorrisReport",
    "MorrisSample",
    "MAX_MORRIS_OBSERVATION_CELLS",
    "MAX_MORRIS_SAMPLES",
    "MAX_MORRIS_WORKERS",
    "MORRIS_PROGRESS_INTERVAL",
    "MORRIS_OBSERVATION_SCHEMA_ID",
    "MORRIS_OBSERVATION_SCHEMA_VERSION",
    "MORRIS_REPORT_SCHEMA_ID",
    "MORRIS_REPORT_SCHEMA_VERSION",
    "NoiseSpec",
    "OutputStats",
    "PairedIntervention",
    "ProgressReport",
    "PropagationResult",
    "PositionDispersion",
    "PositionDispersionAccumulator",
    "PositionNoiseResponseField",
    "PositionNoiseResponsePlotRow",
    "POSITION_NOISE_RESPONSE_FIELD_SCHEMA_ID",
    "POSITION_NOISE_RESPONSE_FIELD_SCHEMA_VERSION",
    "ResponseAccumulatorSnapshot",
    "ResponseFieldAccumulator",
    "ResponseFieldInput",
    "ConfidenceEllipsoidSeries",
    "DispersionMetricSeries",
    "RankedLowVariabilityInterval",
    "RANK_DEFICIENT",
    "RMS_RADIUS",
    "PerturbationGroup",
    "SensitivityResult",
    "TRACE_RESAMPLING_POLICY_ID",
    "TraceResamplingResult",
    "VariableDef",
    "VariationDataset",
    "VariationPlan",
    "dispersion_ellipse",
    "evaluate_morris_design",
    "analyze_morris",
    "morris_observations_from_json_dict",
    "morris_observations_to_json_dict",
    "analyze_paired_intervention",
    "compute_position_dispersion",
    "compute_position_dispersion_view",
    "compute_position_noise_response_field",
    "iter_position_noise_response_plot_rows",
    "response_field_fingerprint",
    "build_confidence_ellipsoids",
    "build_dispersion_metric_series",
    "evaluate_run",
    "keys_for_mode",
    "find_low_variability_intervals",
    "find_ranked_low_variability_intervals",
    "finite_sample_standard_deviation",
    "generate_morris_design",
    "from_json_dict",
    "one_at_a_time_sensitivity",
    "outputs_for_mode",
    "read_csv",
    "read_hdf5",
    "read_json",
    "register_variable",
    "resample_position_traces",
    "run_variation",
    "sensitivity_from_standard_deviations",
    "sample_inputs",
    "sample_input_block",
    "sample_input_chunks",
    "spearman_matrix",
    "summary_stats",
    "to_json_dict",
    "variable_registry",
    "variables_in_category",
    "write_csv",
    "write_hdf5",
    "write_json",
]
