"""Strict reusable flight-to-ground transfer and result contracts."""

from .bounce_kinematics import interpolate_first_contact
from .bounce_request_wire import (
    MAX_REPEATED_BOUNCE_REQUEST_WIRE_BYTES,
    REPEATED_BOUNCE_REQUEST_SCHEMA_VERSION,
    RepeatedBounceRequest,
    RepeatedBounceRequestResultPair,
    repeated_bounce_execution_input_sha256,
    repeated_bounce_request_from_dict,
    repeated_bounce_request_from_json,
    repeated_bounce_request_to_dict,
    repeated_bounce_request_to_json,
)
from .bounce_simulation import simulate_repeated_bounce
from .bounce_types import (
    BounceAirSegment,
    BounceModelSettings,
    BounceTermination,
    BounceTerminationReason,
    RepeatedBounceResult,
)
from .bounce_wire import (
    MAX_REPEATED_BOUNCE_WIRE_BYTES,
    REPEATED_BOUNCE_SCHEMA_VERSION,
    repeated_bounce_result_from_dict,
    repeated_bounce_result_from_json,
    repeated_bounce_result_to_dict,
    repeated_bounce_result_to_json,
)
from .contract_records import GroundSimulationRequest, GroundSimulationResult
from .contract_types import (
    REQUEST_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    UNIT_SYSTEM_SI,
    CalibrationKind,
    GroundCalibration,
    GroundContactState,
    GroundEvent,
    GroundEventType,
    GroundFrame,
    GroundPhase,
    GroundProvenance,
    GroundResultStatus,
    GroundSurfaceProfile,
    GroundTerminationReason,
    GroundTrajectoryPoint,
    GroundWarningSeverity,
)
from .contract_wire import request_from_json, result_from_json
from .ground_result_composer import GroundCompositionError, compose_ground_result
from .impact_impulse import resolve_sphere_plane_impact
from .impact_types import (
    ImpactEnergyLedger,
    ImpactImpulseResult,
    ImpactRegime,
    ImpactRejectionReason,
    ImpactStateError,
    SphereProperties,
)
from .json_schema import (
    JSON_SCHEMA_DIALECT,
    request_json_schema,
    result_json_schema,
    schema_json,
)
from .migration import migrate_request_to_current, migrate_result_to_current
from .regional_execution import (
    MAX_REGIONAL_EXECUTION_STEPS,
    MAX_REGIONAL_EXECUTION_TRANSITIONS,
    REGIONAL_GROUND_EXECUTOR_ID,
    REGIONAL_GROUND_EXECUTOR_SOURCE,
    REGIONAL_GROUND_EXECUTOR_VERSION,
    RegionalGroundExecutionOptions,
    execute_regional_ground,
)
from .regional_execution_records import (
    MAX_REGIONAL_GROUND_EXECUTION_WIRE_BYTES,
    REGIONAL_GROUND_EXECUTION_LIMITATIONS,
    REGIONAL_GROUND_EXECUTION_SCHEMA_VERSION,
    RegionalGroundExecutionFailureReason,
    RegionalGroundExecutionResult,
    RegionalGroundExecutionStatus,
    execution_input_sha256,
)
from .regional_execution_wire import regional_ground_execution_result_from_json
from .regional_plan_contract import (
    MAX_REGIONAL_PLAN_REGIONS,
    MAX_REGIONAL_PLAN_WIRE_BYTES,
    REGIONAL_PLAN_GEOMETRY_MODEL,
    REGIONAL_PLAN_LIMITATIONS,
    REGIONAL_PLAN_REQUEST_SCHEMA_VERSION,
    REGIONAL_PLAN_RESULT_SCHEMA_VERSION,
    GroundRegionalMaterialPlanRequest,
    GroundRegionalMaterialPlanResult,
    GroundRegionalMaterialRegion,
    build_regional_material_plan_result,
    regional_material_plan_request_from_json,
    regional_material_plan_result_from_json,
    regional_plan_to_surface_resolver,
)
from .regional_surface_types import (
    PlanarSurfaceRegion,
    SurfaceRegionTransition,
    SurfaceRegionTransitionCrossing,
)
from .result_adapter import to_ground_model_result
from .result_types import GroundSummary, GroundTermination, GroundWarning
from .skid_roll_result_types import SkidRollResult
from .skid_roll_simulation import SkidRollExecution, simulate_skid_roll
from .surface_motion_types import (
    GROUND_SKID_ROLL_MODEL_ID,
    GROUND_SKID_ROLL_MODEL_VERSION,
    PlanarSurfaceDomain,
    RigidMotion,
    SkidRollEnergyLedger,
    SkidRollSettings,
    SkidRollTermination,
    SkidRollTerminationReason,
    SurfaceBoundaryCrossing,
    SurfaceKinematicSegment,
)
from .surface_resolver import SurfaceResolver
from .unavailable_types import (
    GroundUnavailableField,
    GroundUnavailableFieldId,
    GroundUnavailableReason,
)

__all__ = [
    "REQUEST_SCHEMA_VERSION",
    "RESULT_SCHEMA_VERSION",
    "UNIT_SYSTEM_SI",
    "JSON_SCHEMA_DIALECT",
    "CalibrationKind",
    "BounceModelSettings",
    "BounceAirSegment",
    "BounceTermination",
    "BounceTerminationReason",
    "GroundCalibration",
    "GroundCompositionError",
    "GroundContactState",
    "GroundEvent",
    "GroundEventType",
    "GroundFrame",
    "GroundPhase",
    "GroundProvenance",
    "GroundResultStatus",
    "GroundSimulationRequest",
    "GroundSimulationResult",
    "GroundSummary",
    "GroundSurfaceProfile",
    "GroundTermination",
    "GroundTerminationReason",
    "GroundTrajectoryPoint",
    "GroundUnavailableField",
    "GroundUnavailableFieldId",
    "GroundUnavailableReason",
    "GroundWarning",
    "GroundWarningSeverity",
    "ImpactEnergyLedger",
    "ImpactImpulseResult",
    "ImpactRegime",
    "ImpactRejectionReason",
    "ImpactStateError",
    "GROUND_SKID_ROLL_MODEL_ID",
    "GROUND_SKID_ROLL_MODEL_VERSION",
    "PlanarSurfaceDomain",
    "PlanarSurfaceRegion",
    "MAX_REGIONAL_PLAN_REGIONS",
    "MAX_REGIONAL_PLAN_WIRE_BYTES",
    "REGIONAL_PLAN_GEOMETRY_MODEL",
    "REGIONAL_PLAN_LIMITATIONS",
    "REGIONAL_PLAN_REQUEST_SCHEMA_VERSION",
    "REGIONAL_PLAN_RESULT_SCHEMA_VERSION",
    "GroundRegionalMaterialPlanRequest",
    "GroundRegionalMaterialPlanResult",
    "GroundRegionalMaterialRegion",
    "MAX_REGIONAL_EXECUTION_STEPS",
    "MAX_REGIONAL_EXECUTION_TRANSITIONS",
    "MAX_REGIONAL_GROUND_EXECUTION_WIRE_BYTES",
    "REGIONAL_GROUND_EXECUTION_LIMITATIONS",
    "REGIONAL_GROUND_EXECUTION_SCHEMA_VERSION",
    "REGIONAL_GROUND_EXECUTOR_ID",
    "REGIONAL_GROUND_EXECUTOR_SOURCE",
    "REGIONAL_GROUND_EXECUTOR_VERSION",
    "RegionalGroundExecutionFailureReason",
    "RegionalGroundExecutionOptions",
    "RegionalGroundExecutionResult",
    "RegionalGroundExecutionStatus",
    "RigidMotion",
    "SphereProperties",
    "RepeatedBounceResult",
    "MAX_REPEATED_BOUNCE_WIRE_BYTES",
    "MAX_REPEATED_BOUNCE_REQUEST_WIRE_BYTES",
    "REPEATED_BOUNCE_REQUEST_SCHEMA_VERSION",
    "REPEATED_BOUNCE_SCHEMA_VERSION",
    "RepeatedBounceRequest",
    "RepeatedBounceRequestResultPair",
    "SkidRollEnergyLedger",
    "SkidRollExecution",
    "SkidRollResult",
    "SkidRollSettings",
    "SkidRollTermination",
    "SkidRollTerminationReason",
    "SurfaceBoundaryCrossing",
    "SurfaceKinematicSegment",
    "SurfaceRegionTransition",
    "SurfaceRegionTransitionCrossing",
    "SurfaceResolver",
    "compose_ground_result",
    "execute_regional_ground",
    "execution_input_sha256",
    "build_regional_material_plan_result",
    "interpolate_first_contact",
    "request_from_json",
    "regional_material_plan_request_from_json",
    "regional_material_plan_result_from_json",
    "regional_plan_to_surface_resolver",
    "regional_ground_execution_result_from_json",
    "request_json_schema",
    "result_from_json",
    "result_json_schema",
    "schema_json",
    "migrate_request_to_current",
    "migrate_result_to_current",
    "to_ground_model_result",
    "resolve_sphere_plane_impact",
    "simulate_repeated_bounce",
    "repeated_bounce_result_from_dict",
    "repeated_bounce_result_from_json",
    "repeated_bounce_result_to_dict",
    "repeated_bounce_result_to_json",
    "repeated_bounce_execution_input_sha256",
    "repeated_bounce_request_from_dict",
    "repeated_bounce_request_from_json",
    "repeated_bounce_request_to_dict",
    "repeated_bounce_request_to_json",
    "simulate_skid_roll",
]
