"""Strict reusable flight-to-ground transfer and result contracts."""

from importlib import import_module
from typing import Any

from .bounce_execution import execute_repeated_bounce_request
from .bounce_kinematics import interpolate_first_contact
from .bounce_request_wire import (
    MAX_REPEATED_BOUNCE_REQUEST_WIRE_BYTES,
    REPEATED_BOUNCE_REQUEST_SCHEMA_VERSION,
    RepeatedBounceRequest,
    RepeatedBounceRequestResultPair,
    repeated_bounce_execution_input_sha256,
    repeated_bounce_request_from_dict,
    repeated_bounce_request_from_json,
    repeated_bounce_request_to_dict,
    repeated_bounce_request_to_json,
)
from .bounce_simulation import simulate_repeated_bounce
from .bounce_types import (
    BounceAirSegment,
    BounceModelSettings,
    BounceTermination,
    BounceTerminationReason,
    RepeatedBounceResult,
)
from .bounce_wire import (
    MAX_REPEATED_BOUNCE_WIRE_BYTES,
    REPEATED_BOUNCE_SCHEMA_VERSION,
    repeated_bounce_result_from_dict,
    repeated_bounce_result_from_json,
    repeated_bounce_result_to_dict,
    repeated_bounce_result_to_json,
)
from .contract_records import GroundSimulationRequest, GroundSimulationResult
from .contract_types import (
    REQUEST_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    UNIT_SYSTEM_SI,
    CalibrationKind,
    GroundCalibration,
    GroundContactState,
    GroundEvent,
    GroundEventType,
    GroundFrame,
    GroundPhase,
    GroundProvenance,
    GroundResultStatus,
    GroundSurfaceProfile,
    GroundTerminationReason,
    GroundTrajectoryPoint,
    GroundWarningSeverity,
)
from .contract_wire import request_from_json, result_from_json
from .ground_result_composer import GroundCompositionError, compose_ground_result
from .impact_impulse import resolve_sphere_plane_impact
from .impact_types import (
    ImpactEnergyLedger,
    ImpactImpulseResult,
    ImpactRegime,
    ImpactRejectionReason,
    ImpactStateError,
    SphereProperties,
)
from .json_schema import (
    JSON_SCHEMA_DIALECT,
    request_json_schema,
    result_json_schema,
    schema_json,
)
from .migration import migrate_request_to_current, migrate_result_to_current
from .profile_binding import (
    PROFILE_ILLUSTRATIVE_WARNING,
    PROFILE_UNQUALIFIED_WARNING,
    BoundGroundSurface,
    ProfileOperatingCondition,
    SurfacePlacement,
    bind_material_profile,
)
from .profile_enums import (
    CANONICAL_GROUND_PARAMETER_IDS,
    GROUND_MATERIAL_PROFILE_SCHEMA_VERSION,
    GROUND_PROFILE_LIBRARY_SCHEMA_VERSION,
    GroundEvidenceKind,
    GroundModelUseStatus,
    GroundParameterId,
    GroundQualificationGateId,
    GroundQualificationStatus,
)
from .profile_migration import migrate_library_to_current, migrate_profile_to_current
from .profile_schema import (
    library_json_schema,
    profile_json_schema,
    validate_library_payload,
    validate_profile_payload,
)
from .profile_schema import (
    schema_json as profile_schema_json,
)
from .profile_store import (
    DEFAULT_PROFILE_LIBRARY_FILENAME,
    DEFAULT_PROFILE_LIBRARY_MAX_BYTES,
    GroundProfileLibraryStore,
    ProfileStoreConflictError,
    ProfileStoreCorruptionError,
    ProfileStoreError,
    ProfileStoreIndeterminateCommitError,
    ProfileStoreLockError,
    ProfileStorePathError,
    StoredGroundProfileLibrary,
)
from .profile_types import (
    GroundApplicability,
    GroundCalibrationRecord,
    GroundMaterialParameter,
    GroundMaterialProfile,
    GroundProfileEvidence,
    GroundProfileLibrary,
    GroundProfileProvenance,
    GroundProfileQualification,
    GroundProfileRights,
    GroundQualificationGate,
)
from .profile_wire import (
    document_from_dict,
    document_to_dict,
    document_to_json,
    library_from_json,
    profile_from_json,
)
from .regional_execution import (
    MAX_REGIONAL_EXECUTION_STEPS,
    MAX_REGIONAL_EXECUTION_TRANSITIONS,
    REGIONAL_GROUND_EXECUTOR_ID,
    REGIONAL_GROUND_EXECUTOR_SOURCE,
    REGIONAL_GROUND_EXECUTOR_VERSION,
    RegionalGroundExecutionOptions,
    execute_regional_ground,
)
from .regional_execution_records import (
    MAX_REGIONAL_GROUND_EXECUTION_WIRE_BYTES,
    REGIONAL_GROUND_EXECUTION_LIMITATIONS,
    REGIONAL_GROUND_EXECUTION_SCHEMA_VERSION,
    RegionalGroundExecutionFailureReason,
    RegionalGroundExecutionResult,
    RegionalGroundExecutionStatus,
    execution_input_sha256,
)
from .regional_execution_wire import regional_ground_execution_result_from_json
from .regional_plan_contract import (
    MAX_REGIONAL_PLAN_REGIONS,
    MAX_REGIONAL_PLAN_WIRE_BYTES,
    REGIONAL_PLAN_GEOMETRY_MODEL,
    REGIONAL_PLAN_LIMITATIONS,
    REGIONAL_PLAN_REQUEST_SCHEMA_VERSION,
    REGIONAL_PLAN_RESULT_SCHEMA_VERSION,
    GroundRegionalMaterialPlanRequest,
    GroundRegionalMaterialPlanResult,
    GroundRegionalMaterialRegion,
    build_regional_material_plan_result,
    regional_material_plan_request_from_json,
    regional_material_plan_result_from_json,
    regional_plan_to_surface_resolver,
)
from .regional_surface_types import (
    PlanarSurfaceRegion,
    SurfaceRegionTransition,
    SurfaceRegionTransitionCrossing,
)
from .result_types import GroundSummary, GroundTermination, GroundWarning
from .skid_roll_result_types import SkidRollResult
from .skid_roll_simulation import SkidRollExecution, simulate_skid_roll
from .surface_motion_types import (
    GROUND_SKID_ROLL_MODEL_ID,
    GROUND_SKID_ROLL_MODEL_VERSION,
    PlanarSurfaceDomain,
    RigidMotion,
    SkidRollEnergyLedger,
    SkidRollSettings,
    SkidRollTermination,
    SkidRollTerminationReason,
    SurfaceBoundaryCrossing,
    SurfaceKinematicSegment,
)
from .surface_resolver import SurfaceResolver
from .unavailable_types import (
    GroundUnavailableField,
    GroundUnavailableFieldId,
    GroundUnavailableReason,
)
from .upstream_terrain_adapter import (
    UPSTREAM_TERRAIN_ADAPTER_VERSION,
    UPSTREAM_TERRAIN_SNAPSHOT_SCHEMA_VERSION,
    AdaptedTerrainSurface,
    FrameTransform,
    TerrainAdapterInterpretation,
    TerrainDispositionKind,
    TerrainFieldDisposition,
    UpstreamTerrainSnapshot,
    adapt_upstream_terrain_snapshot,
    upstream_snapshot_from_json,
)

_LAZY_EXPORTS = {
    "GROUND_REFERENCE_EXECUTION_SCHEMA_VERSION": "reference_execution_types",
    "GROUND_STUDY_SCHEMA_VERSION": "study_types",
    "GroundEndpointKind": "study_types",
    "GroundReferenceCancelled": "reference_execution_types",
    "GroundReferenceExecution": "reference_execution_types",
    "GroundReferenceExecutionError": "reference_execution_types",
    "GroundReferencePhase": "reference_execution_types",
    "GroundSolverEligibility": "study_types",
    "GroundSolverEligibilityReason": "study_types",
    "GroundStudyMetrics": "study_types",
    "GroundStudyProfile": "study_types",
    "GroundStudyProjection": "study_record",
    "GroundStudyStatus": "study_types",
    "GroundTargetEvaluation": "study_types",
    "GroundTargetUnavailableReason": "study_types",
    "project_ground_study": "study_projection",
    "qualified_study_to_ground_model_result": "result_adapter",
    "run_ground_reference": "reference_execution",
}


def __getattr__(name: str) -> Any:
    """Load solver-dependent exports without creating import cycles."""
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f"{__name__}.{module_name}"), name)
    globals()[name] = value
    return value


__all__ = [
    "REQUEST_SCHEMA_VERSION",
    "RESULT_SCHEMA_VERSION",
    "UNIT_SYSTEM_SI",
    "JSON_SCHEMA_DIALECT",
    "CANONICAL_GROUND_PARAMETER_IDS",
    "DEFAULT_PROFILE_LIBRARY_FILENAME",
    "DEFAULT_PROFILE_LIBRARY_MAX_BYTES",
    "GROUND_MATERIAL_PROFILE_SCHEMA_VERSION",
    "GROUND_PROFILE_LIBRARY_SCHEMA_VERSION",
    "GROUND_REFERENCE_EXECUTION_SCHEMA_VERSION",
    "GROUND_STUDY_SCHEMA_VERSION",
    "PROFILE_UNQUALIFIED_WARNING",
    "PROFILE_ILLUSTRATIVE_WARNING",
    "UPSTREAM_TERRAIN_ADAPTER_VERSION",
    "UPSTREAM_TERRAIN_SNAPSHOT_SCHEMA_VERSION",
    "AdaptedTerrainSurface",
    "BoundGroundSurface",
    "CalibrationKind",
    "BounceModelSettings",
    "BounceAirSegment",
    "BounceTermination",
    "BounceTerminationReason",
    "GroundCalibration",
    "GroundCalibrationRecord",
    "GroundApplicability",
    "GroundCompositionError",
    "GroundContactState",
    "GroundEvent",
    "GroundEventType",
    "GroundEndpointKind",
    "GroundFrame",
    "GroundEvidenceKind",
    "GroundMaterialParameter",
    "GroundMaterialProfile",
    "GroundModelUseStatus",
    "GroundParameterId",
    "GroundPhase",
    "GroundProvenance",
    "GroundProfileEvidence",
    "GroundProfileLibrary",
    "GroundProfileLibraryStore",
    "GroundProfileProvenance",
    "GroundProfileQualification",
    "GroundProfileRights",
    "GroundReferenceCancelled",
    "GroundReferenceExecution",
    "GroundReferenceExecutionError",
    "GroundReferencePhase",
    "GroundQualificationGate",
    "GroundQualificationGateId",
    "GroundQualificationStatus",
    "GroundResultStatus",
    "GroundSimulationRequest",
    "GroundSimulationResult",
    "GroundSolverEligibility",
    "GroundSolverEligibilityReason",
    "GroundStudyMetrics",
    "GroundStudyProfile",
    "GroundStudyProjection",
    "GroundStudyStatus",
    "GroundSummary",
    "GroundSurfaceProfile",
    "GroundTermination",
    "GroundTerminationReason",
    "GroundTargetEvaluation",
    "GroundTargetUnavailableReason",
    "GroundTrajectoryPoint",
    "GroundUnavailableField",
    "GroundUnavailableFieldId",
    "GroundUnavailableReason",
    "GroundWarning",
    "GroundWarningSeverity",
    "ImpactEnergyLedger",
    "ImpactImpulseResult",
    "ImpactRegime",
    "ImpactRejectionReason",
    "ImpactStateError",
    "FrameTransform",
    "GROUND_SKID_ROLL_MODEL_ID",
    "GROUND_SKID_ROLL_MODEL_VERSION",
    "PlanarSurfaceDomain",
    "PlanarSurfaceRegion",
    "MAX_REGIONAL_PLAN_REGIONS",
    "MAX_REGIONAL_PLAN_WIRE_BYTES",
    "REGIONAL_PLAN_GEOMETRY_MODEL",
    "REGIONAL_PLAN_LIMITATIONS",
    "REGIONAL_PLAN_REQUEST_SCHEMA_VERSION",
    "REGIONAL_PLAN_RESULT_SCHEMA_VERSION",
    "GroundRegionalMaterialPlanRequest",
    "GroundRegionalMaterialPlanResult",
    "GroundRegionalMaterialRegion",
    "MAX_REGIONAL_EXECUTION_STEPS",
    "MAX_REGIONAL_EXECUTION_TRANSITIONS",
    "MAX_REGIONAL_GROUND_EXECUTION_WIRE_BYTES",
    "REGIONAL_GROUND_EXECUTION_LIMITATIONS",
    "REGIONAL_GROUND_EXECUTION_SCHEMA_VERSION",
    "REGIONAL_GROUND_EXECUTOR_ID",
    "REGIONAL_GROUND_EXECUTOR_SOURCE",
    "REGIONAL_GROUND_EXECUTOR_VERSION",
    "RegionalGroundExecutionFailureReason",
    "RegionalGroundExecutionOptions",
    "RegionalGroundExecutionResult",
    "RegionalGroundExecutionStatus",
    "ProfileOperatingCondition",
    "ProfileStoreConflictError",
    "ProfileStoreCorruptionError",
    "ProfileStoreError",
    "ProfileStoreIndeterminateCommitError",
    "ProfileStoreLockError",
    "ProfileStorePathError",
    "RigidMotion",
    "SphereProperties",
    "RepeatedBounceResult",
    "MAX_REPEATED_BOUNCE_WIRE_BYTES",
    "MAX_REPEATED_BOUNCE_REQUEST_WIRE_BYTES",
    "REPEATED_BOUNCE_REQUEST_SCHEMA_VERSION",
    "REPEATED_BOUNCE_SCHEMA_VERSION",
    "RepeatedBounceRequest",
    "RepeatedBounceRequestResultPair",
    "SkidRollEnergyLedger",
    "SkidRollExecution",
    "SkidRollResult",
    "SkidRollSettings",
    "SkidRollTermination",
    "SkidRollTerminationReason",
    "SurfaceBoundaryCrossing",
    "SurfaceKinematicSegment",
    "SurfaceRegionTransition",
    "SurfaceRegionTransitionCrossing",
    "SurfaceResolver",
    "SurfacePlacement",
    "StoredGroundProfileLibrary",
    "TerrainAdapterInterpretation",
    "TerrainDispositionKind",
    "TerrainFieldDisposition",
    "UpstreamTerrainSnapshot",
    "adapt_upstream_terrain_snapshot",
    "bind_material_profile",
    "compose_ground_result",
    "execute_repeated_bounce_request",
    "execute_regional_ground",
    "execution_input_sha256",
    "build_regional_material_plan_result",
    "interpolate_first_contact",
    "document_from_dict",
    "document_to_dict",
    "document_to_json",
    "library_from_json",
    "library_json_schema",
    "migrate_library_to_current",
    "migrate_profile_to_current",
    "profile_from_json",
    "profile_json_schema",
    "profile_schema_json",
    "project_ground_study",
    "qualified_study_to_ground_model_result",
    "request_from_json",
    "regional_material_plan_request_from_json",
    "regional_material_plan_result_from_json",
    "regional_plan_to_surface_resolver",
    "regional_ground_execution_result_from_json",
    "request_json_schema",
    "result_from_json",
    "result_json_schema",
    "schema_json",
    "migrate_request_to_current",
    "migrate_result_to_current",
    "resolve_sphere_plane_impact",
    "run_ground_reference",
    "simulate_repeated_bounce",
    "repeated_bounce_result_from_dict",
    "repeated_bounce_result_from_json",
    "repeated_bounce_result_to_dict",
    "repeated_bounce_result_to_json",
    "repeated_bounce_execution_input_sha256",
    "repeated_bounce_request_from_dict",
    "repeated_bounce_request_from_json",
    "repeated_bounce_request_to_dict",
    "repeated_bounce_request_to_json",
    "simulate_skid_roll",
    "upstream_snapshot_from_json",
    "validate_library_payload",
    "validate_profile_payload",
]
