"""Strict reusable flight-to-ground transfer and result contracts."""

from .bounce_kinematics import interpolate_first_contact
from .bounce_simulation import simulate_repeated_bounce
from .bounce_types import (
    BounceAirSegment,
    BounceModelSettings,
    BounceTermination,
    BounceTerminationReason,
    RepeatedBounceResult,
)
from .contract_records import GroundSimulationRequest, GroundSimulationResult
from .contract_types import (
    REQUEST_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    UNIT_SYSTEM_SI,
    CalibrationKind,
    GroundCalibration,
    GroundContactState,
    GroundEvent,
    GroundEventType,
    GroundFrame,
    GroundPhase,
    GroundProvenance,
    GroundResultStatus,
    GroundSurfaceProfile,
    GroundTerminationReason,
    GroundTrajectoryPoint,
    GroundWarningSeverity,
)
from .contract_wire import request_from_json, result_from_json
from .ground_result_composer import GroundCompositionError, compose_ground_result
from .impact_impulse import resolve_sphere_plane_impact
from .impact_types import (
    ImpactEnergyLedger,
    ImpactImpulseResult,
    ImpactRegime,
    ImpactRejectionReason,
    ImpactStateError,
    SphereProperties,
)
from .json_schema import (
    JSON_SCHEMA_DIALECT,
    request_json_schema,
    result_json_schema,
    schema_json,
)
from .migration import migrate_request_to_current, migrate_result_to_current
from .profile_binding import (
    PROFILE_ILLUSTRATIVE_WARNING,
    PROFILE_UNQUALIFIED_WARNING,
    BoundGroundSurface,
    ProfileOperatingCondition,
    SurfacePlacement,
    bind_material_profile,
)
from .profile_enums import (
    CANONICAL_GROUND_PARAMETER_IDS,
    GROUND_MATERIAL_PROFILE_SCHEMA_VERSION,
    GROUND_PROFILE_LIBRARY_SCHEMA_VERSION,
    GroundEvidenceKind,
    GroundModelUseStatus,
    GroundParameterId,
    GroundQualificationGateId,
    GroundQualificationStatus,
)
from .profile_migration import migrate_library_to_current, migrate_profile_to_current
from .profile_schema import (
    library_json_schema,
    profile_json_schema,
    validate_library_payload,
    validate_profile_payload,
)
from .profile_schema import (
    schema_json as profile_schema_json,
)
from .profile_store import (
    DEFAULT_PROFILE_LIBRARY_FILENAME,
    DEFAULT_PROFILE_LIBRARY_MAX_BYTES,
    GroundProfileLibraryStore,
    ProfileStoreConflictError,
    ProfileStoreCorruptionError,
    ProfileStoreError,
    ProfileStoreIndeterminateCommitError,
    ProfileStoreLockError,
    ProfileStorePathError,
    StoredGroundProfileLibrary,
)
from .profile_types import (
    GroundApplicability,
    GroundCalibrationRecord,
    GroundMaterialParameter,
    GroundMaterialProfile,
    GroundProfileEvidence,
    GroundProfileLibrary,
    GroundProfileProvenance,
    GroundProfileQualification,
    GroundProfileRights,
    GroundQualificationGate,
)
from .profile_wire import (
    document_from_dict,
    document_to_dict,
    document_to_json,
    library_from_json,
    profile_from_json,
)
from .result_adapter import to_ground_model_result
from .result_types import GroundSummary, GroundTermination, GroundWarning
from .skid_roll_simulation import SkidRollExecution, simulate_skid_roll
from .study_projection import project_ground_study
from .study_record import GroundStudyProjection
from .study_types import (
    GROUND_STUDY_SCHEMA_VERSION,
    GroundEndpointKind,
    GroundSolverEligibility,
    GroundSolverEligibilityReason,
    GroundStudyMetrics,
    GroundStudyProfile,
    GroundStudyStatus,
    GroundTargetEvaluation,
    GroundTargetUnavailableReason,
)
from .surface_motion_types import (
    GROUND_SKID_ROLL_MODEL_ID,
    GROUND_SKID_ROLL_MODEL_VERSION,
    PlanarSurfaceDomain,
    RigidMotion,
    SkidRollEnergyLedger,
    SkidRollResult,
    SkidRollSettings,
    SkidRollTermination,
    SkidRollTerminationReason,
    SurfaceBoundaryCrossing,
    SurfaceKinematicSegment,
)
from .surface_resolver import SurfaceResolver
from .unavailable_types import (
    GroundUnavailableField,
    GroundUnavailableFieldId,
    GroundUnavailableReason,
)
from .upstream_terrain_adapter import (
    UPSTREAM_TERRAIN_ADAPTER_VERSION,
    UPSTREAM_TERRAIN_SNAPSHOT_SCHEMA_VERSION,
    AdaptedTerrainSurface,
    FrameTransform,
    TerrainAdapterInterpretation,
    TerrainDispositionKind,
    TerrainFieldDisposition,
    UpstreamTerrainSnapshot,
    adapt_upstream_terrain_snapshot,
    upstream_snapshot_from_json,
)

__all__ = [
    "REQUEST_SCHEMA_VERSION",
    "RESULT_SCHEMA_VERSION",
    "UNIT_SYSTEM_SI",
    "JSON_SCHEMA_DIALECT",
    "CANONICAL_GROUND_PARAMETER_IDS",
    "DEFAULT_PROFILE_LIBRARY_FILENAME",
    "DEFAULT_PROFILE_LIBRARY_MAX_BYTES",
    "GROUND_MATERIAL_PROFILE_SCHEMA_VERSION",
    "GROUND_PROFILE_LIBRARY_SCHEMA_VERSION",
    "GROUND_STUDY_SCHEMA_VERSION",
    "PROFILE_UNQUALIFIED_WARNING",
    "PROFILE_ILLUSTRATIVE_WARNING",
    "UPSTREAM_TERRAIN_ADAPTER_VERSION",
    "UPSTREAM_TERRAIN_SNAPSHOT_SCHEMA_VERSION",
    "AdaptedTerrainSurface",
    "BoundGroundSurface",
    "CalibrationKind",
    "BounceModelSettings",
    "BounceAirSegment",
    "BounceTermination",
    "BounceTerminationReason",
    "GroundCalibration",
    "GroundCalibrationRecord",
    "GroundApplicability",
    "GroundCompositionError",
    "GroundContactState",
    "GroundEvent",
    "GroundEventType",
    "GroundEndpointKind",
    "GroundFrame",
    "GroundEvidenceKind",
    "GroundMaterialParameter",
    "GroundMaterialProfile",
    "GroundModelUseStatus",
    "GroundParameterId",
    "GroundPhase",
    "GroundProvenance",
    "GroundProfileEvidence",
    "GroundProfileLibrary",
    "GroundProfileLibraryStore",
    "GroundProfileProvenance",
    "GroundProfileQualification",
    "GroundProfileRights",
    "GroundQualificationGate",
    "GroundQualificationGateId",
    "GroundQualificationStatus",
    "GroundResultStatus",
    "GroundSimulationRequest",
    "GroundSimulationResult",
    "GroundSolverEligibility",
    "GroundSolverEligibilityReason",
    "GroundStudyMetrics",
    "GroundStudyProfile",
    "GroundStudyProjection",
    "GroundStudyStatus",
    "GroundSummary",
    "GroundSurfaceProfile",
    "GroundTermination",
    "GroundTerminationReason",
    "GroundTargetEvaluation",
    "GroundTargetUnavailableReason",
    "GroundTrajectoryPoint",
    "GroundUnavailableField",
    "GroundUnavailableFieldId",
    "GroundUnavailableReason",
    "GroundWarning",
    "GroundWarningSeverity",
    "ImpactEnergyLedger",
    "ImpactImpulseResult",
    "ImpactRegime",
    "ImpactRejectionReason",
    "ImpactStateError",
    "FrameTransform",
    "GROUND_SKID_ROLL_MODEL_ID",
    "GROUND_SKID_ROLL_MODEL_VERSION",
    "PlanarSurfaceDomain",
    "ProfileOperatingCondition",
    "ProfileStoreConflictError",
    "ProfileStoreCorruptionError",
    "ProfileStoreError",
    "ProfileStoreIndeterminateCommitError",
    "ProfileStoreLockError",
    "ProfileStorePathError",
    "RigidMotion",
    "SphereProperties",
    "RepeatedBounceResult",
    "SkidRollEnergyLedger",
    "SkidRollExecution",
    "SkidRollResult",
    "SkidRollSettings",
    "SkidRollTermination",
    "SkidRollTerminationReason",
    "SurfaceBoundaryCrossing",
    "SurfaceKinematicSegment",
    "SurfaceResolver",
    "SurfacePlacement",
    "StoredGroundProfileLibrary",
    "TerrainAdapterInterpretation",
    "TerrainDispositionKind",
    "TerrainFieldDisposition",
    "UpstreamTerrainSnapshot",
    "adapt_upstream_terrain_snapshot",
    "bind_material_profile",
    "compose_ground_result",
    "interpolate_first_contact",
    "document_from_dict",
    "document_to_dict",
    "document_to_json",
    "library_from_json",
    "library_json_schema",
    "migrate_library_to_current",
    "migrate_profile_to_current",
    "profile_from_json",
    "profile_json_schema",
    "profile_schema_json",
    "project_ground_study",
    "request_from_json",
    "request_json_schema",
    "result_from_json",
    "result_json_schema",
    "schema_json",
    "migrate_request_to_current",
    "migrate_result_to_current",
    "to_ground_model_result",
    "resolve_sphere_plane_impact",
    "simulate_repeated_bounce",
    "simulate_skid_roll",
    "upstream_snapshot_from_json",
    "validate_library_payload",
    "validate_profile_payload",
]
