"""
Utils package providing common utilities across the repository.

This package contains:
- logging_utils: Logging configuration and utilities
- error_handling: Error handling decorators and utilities
- test_utils: Testing utilities, fixtures, and assertions
- debug_utils: Debugging, profiling, and diagnostic tools
- integration_test_helpers: Integration test base classes and helpers
"""

from utils.debug_utils import (
    MemoryStats,
    PerformanceWatchdog,
    ProfileResult,
    StackFrame,
    SystemDiagnostics,
    TimingStats,
    debug_exception,
    debug_log,
    debug_only,
    debug_vars,
    deprecated,
    get_call_stack,
    get_caller_info,
    get_memory_usage,
    get_system_diagnostics,
    get_watchdog,
    is_debug_mode,
    memory_profile,
    memory_tracker,
    profile,
    profile_block,
    set_debug_mode,
    timed,
    timer,
    trace_calls,
)
from utils.error_handling import (
    exit_on_error,
    handle_file_errors,
    handle_import_error,
    log_and_continue,
    safe_execute,
)
from utils.logging_utils import (
    DEFAULT_FORMAT,
    DEFAULT_SEED,
    SIMPLE_FORMAT,
    JsonFormatter,
    get_logger,
    init_default_logging,
    set_seeds,
    setup_logging,
)
from utils.test_utils import (
    AssertionHelpers,
    BaseTestCase,
    DataGeneratorConfig,
    IntegrationTestCase,
    MockFactory,
    PytestMarkers,
    TestDataConfig,
    TestMarkers,
    TimingResult,
    assert_helpers,
    assert_performance,
    captured_logs,
    captured_output,
    environment_variables,
    generate_edge_case_data,
    generate_sample_data,
    markers,
    mock_datetime,
    retry_on_failure,
    skip_if_no_module,
    temporary_directory,
    temporary_file,
    time_function,
)

__all__ = [
    # logging_utils
    "DEFAULT_FORMAT",
    "DEFAULT_SEED",
    "SIMPLE_FORMAT",
    "JsonFormatter",
    "get_logger",
    "init_default_logging",
    "set_seeds",
    "setup_logging",
    # error_handling
    "exit_on_error",
    "handle_file_errors",
    "handle_import_error",
    "log_and_continue",
    "safe_execute",
    # test_utils
    "AssertionHelpers",
    "BaseTestCase",
    "DataGeneratorConfig",
    "IntegrationTestCase",
    "MockFactory",
    "PytestMarkers",
    "TestDataConfig",  # Alias for DataGeneratorConfig
    "TestMarkers",  # Alias for PytestMarkers
    "TimingResult",
    "assert_helpers",
    "assert_performance",
    "captured_logs",
    "captured_output",
    "environment_variables",
    "generate_edge_case_data",
    "generate_sample_data",
    "markers",
    "mock_datetime",
    "retry_on_failure",
    "skip_if_no_module",
    "temporary_directory",
    "temporary_file",
    "time_function",
    # debug_utils
    "MemoryStats",
    "PerformanceWatchdog",
    "ProfileResult",
    "StackFrame",
    "SystemDiagnostics",
    "TimingStats",
    "debug_exception",
    "debug_log",
    "debug_only",
    "debug_vars",
    "deprecated",
    "get_call_stack",
    "get_caller_info",
    "get_memory_usage",
    "get_system_diagnostics",
    "get_watchdog",
    "is_debug_mode",
    "memory_profile",
    "memory_tracker",
    "profile",
    "profile_block",
    "set_debug_mode",
    "timed",
    "timer",
    "trace_calls",
]
