"""Canonical UI-independent domain contracts for modular golf clubs.

All positions and lengths are metres, masses kilograms, and inertia tensors
kilogram-metres squared. Every transform declares both frames and maps local
component coordinates into the assembly frame.
"""

from .assembly import ClubAssembly, assemble_mass_properties
from .fitting_document import (
    FITTING_DOCUMENT_FORMAT,
    ClubFittingDocument,
    FaceGeometry,
    FittingProvenance,
    MeshReference,
    fitting_document_from_json,
    fitting_document_to_json,
)
from .fitting_engine import (
    FITTING_REPORT_FORMAT,
    ClubOutcome,
    CounterfactualSpec,
    FittingReport,
    compare_counterfactuals,
    evaluate_club,
    evaluate_counterfactual_set,
    fitting_report_to_json,
)
from .impact_coupling import (
    IMPACT_COUPLING_REPORT_FORMAT,
    CoupledImpactConfig,
    CoupledImpactResult,
    GripBoundary,
    impact_coupling_report,
    simulate_coupled_impact,
)
from .mesh_mass_properties import (
    MeshInertiaReport,
    is_watertight,
    mesh_inertia,
    mesh_volume_centroid,
)
from .putter_fitting import (
    PUTTER_FITTING_REPORT_FORMAT,
    PutterCounterfactual,
    PutterFittingReport,
    PuttingOutcome,
    compare_putter_counterfactuals,
    putter_fitting_report_to_json,
    scenario_for_head,
)
from .putter_head import (
    PUTTER_CONTACT_TIME_S,
    PutterHeadDocument,
    PutterHeadProvenance,
    PutterStrikeResult,
    PutterTwist,
    head_moi_for_strike,
    putter_head_from_library,
    putter_head_from_mesh,
    putter_head_from_stl,
    putter_spec,
    strike_with_head,
    twist_response,
)
from .putter_head_serde import (
    PUTTER_HEAD_FORMAT,
    putter_head_from_json,
    putter_head_to_json,
)
from .serialization import (
    CURRENT_FORMAT,
    LEGACY_FORMAT,
    assembly_from_json,
    assembly_from_json_dict,
    assembly_to_json,
    assembly_to_json_dict,
)
from .shaft_assembly import shaft_component_mass_properties
from .shaft_delivery import (
    GripKinematics,
    ShaftDeliveryDeltas,
    ShaftTipMass,
    solve_shaft_delivery,
)
from .shaft_dynamics import (
    ShaftModalResponse,
    ShaftModalSettings,
    solve_shaft_bending_modes,
)
from .shaft_profile import (
    ExtrapolationPolicy,
    ShaftProfile,
    ShaftProfileProvenance,
    ShaftStation,
)
from .shaft_scaling import ShaftProfileScaling, scale_shaft_profile
from .shaft_serialization import (
    SHAFT_PROFILE_FORMAT,
    shaft_profile_from_csv,
    shaft_profile_from_json,
    shaft_profile_from_json_dict,
    shaft_profile_to_csv,
    shaft_profile_to_json,
    shaft_profile_to_json_dict,
)
from .shaft_statics import (
    ShaftTipLoad,
    ShaftTipResponse,
    solve_cantilever_tip_response,
)
from .turf_contact import (
    TurfCalibrationStatus,
    TurfContactKinematics,
    TurfContactProfile,
    TurfContactResponse,
    TurfContactStatus,
    TurfPreset,
    TurfProfileProvenance,
    evaluate_turf_contact,
    turf_profile_preset,
)
from .turf_convergence import TurfConvergenceStudy, run_turf_convergence_study
from .turf_dynamics import ReducedTurfContactResult, simulate_reduced_turf_contact
from .turf_serialization import (
    TURF_PROFILE_FORMAT,
    turf_profile_from_json,
    turf_profile_from_json_dict,
    turf_profile_to_json,
    turf_profile_to_json_dict,
)
from .turf_variation import (
    CATEGORY_TURF,
    TURF_DAMPING_KEY,
    TURF_FRICTION_KEY,
    TURF_PENETRATION_LIMIT_KEY,
    TURF_STIFFNESS_KEY,
    TURF_VARIABLE_KEYS,
    TurfVariationPlan,
    turf_profiles_for_variation_plan,
)
from .types import (
    AssembledMassProperties,
    ClubComponent,
    ClubLengthConvention,
    ClubLengthMeasurement,
    ComponentMassProperties,
    ComponentRole,
    RigidTransform,
)
from .wedge_cad import WedgeMeasuredMetrics, WedgeSolidResult, build_wedge_solid
from .wedge_export import (
    WEDGE_EXPORT_FORMAT,
    WedgeExportArtifact,
    WedgeExportFormat,
    WedgeExportRequest,
    WedgeExportResult,
    export_wedge_artifacts,
)
from .wedge_geometry import (
    WedgeContactCandidate,
    WedgeContactFeature,
    wedge_body_profile_m,
    wedge_contact_candidates,
    wedge_face_contact_point_m,
)
from .wedge_ground_contact import (
    ContactSequence,
    GroundPlane,
    WedgeClearanceSample,
    WedgeGroundClearanceAnalysis,
    WedgeGroundContactEvent,
    analyze_wedge_ground_clearance,
)
from .wedge_ground_serialization import (
    WEDGE_GROUND_CLEARANCE_FORMAT,
    wedge_ground_clearance_to_json_dict,
)
from .wedge_kinematics import (
    InstantaneousScrewAxis,
    WedgeKinematicAnalysis,
    WedgeKinematicState,
    analyze_wedge_kinematics,
    angle_of_attack_deg,
)
from .wedge_parameters import (
    Handedness,
    WedgeGeometryProvenance,
    WedgeHeadParameters,
    WedgePreset,
    wedge_preset,
)
from .wedge_serialization import (
    WEDGE_PARAMETERS_FORMAT,
    wedge_parameters_from_json,
    wedge_parameters_to_json,
)
from .wedge_turf_interaction import (
    WedgeTurfPatchResponse,
    WedgeTurfWrench,
    evaluate_wedge_turf_wrench,
)

__all__ = [
    "CURRENT_FORMAT",
    "CATEGORY_TURF",
    "LEGACY_FORMAT",
    "AssembledMassProperties",
    "ClubAssembly",
    "ClubComponent",
    "ClubLengthConvention",
    "ClubLengthMeasurement",
    "ComponentMassProperties",
    "ComponentRole",
    "ContactSequence",
    "ExtrapolationPolicy",
    "Handedness",
    "GroundPlane",
    "InstantaneousScrewAxis",
    "RigidTransform",
    "ReducedTurfContactResult",
    "SHAFT_PROFILE_FORMAT",
    "ShaftProfile",
    "ShaftProfileProvenance",
    "ShaftProfileScaling",
    "ShaftStation",
    "ShaftModalResponse",
    "ShaftModalSettings",
    "ShaftTipLoad",
    "ShaftTipResponse",
    "TURF_PROFILE_FORMAT",
    "TURF_DAMPING_KEY",
    "TURF_FRICTION_KEY",
    "TURF_PENETRATION_LIMIT_KEY",
    "TURF_STIFFNESS_KEY",
    "TURF_VARIABLE_KEYS",
    "TurfVariationPlan",
    "TurfCalibrationStatus",
    "TurfContactKinematics",
    "TurfContactProfile",
    "TurfContactResponse",
    "TurfContactStatus",
    "TurfConvergenceStudy",
    "TurfPreset",
    "TurfProfileProvenance",
    "WedgeHeadParameters",
    "WedgeClearanceSample",
    "WedgeContactCandidate",
    "WedgeContactFeature",
    "WedgeGroundClearanceAnalysis",
    "WedgeGroundContactEvent",
    "WedgeTurfPatchResponse",
    "WedgeTurfWrench",
    "WedgeKinematicAnalysis",
    "WedgeKinematicState",
    "WedgeGeometryProvenance",
    "WEDGE_EXPORT_FORMAT",
    "WEDGE_GROUND_CLEARANCE_FORMAT",
    "WedgeExportArtifact",
    "WedgeExportFormat",
    "WedgeExportRequest",
    "WedgeExportResult",
    "WedgeMeasuredMetrics",
    "WedgePreset",
    "WedgeSolidResult",
    "WEDGE_PARAMETERS_FORMAT",
    "assemble_mass_properties",
    "analyze_wedge_kinematics",
    "analyze_wedge_ground_clearance",
    "angle_of_attack_deg",
    "assembly_from_json",
    "assembly_from_json_dict",
    "assembly_to_json",
    "assembly_to_json_dict",
    "build_wedge_solid",
    "export_wedge_artifacts",
    "evaluate_turf_contact",
    "evaluate_wedge_turf_wrench",
    "FITTING_DOCUMENT_FORMAT",
    "ClubFittingDocument",
    "FaceGeometry",
    "FittingProvenance",
    "MeshReference",
    "fitting_document_from_json",
    "fitting_document_to_json",
    "FITTING_REPORT_FORMAT",
    "ClubOutcome",
    "CounterfactualSpec",
    "FittingReport",
    "compare_counterfactuals",
    "evaluate_club",
    "evaluate_counterfactual_set",
    "fitting_report_to_json",
    "IMPACT_COUPLING_REPORT_FORMAT",
    "CoupledImpactConfig",
    "CoupledImpactResult",
    "GripBoundary",
    "impact_coupling_report",
    "simulate_coupled_impact",
    "MeshInertiaReport",
    "is_watertight",
    "mesh_inertia",
    "mesh_volume_centroid",
    "PUTTER_CONTACT_TIME_S",
    "PUTTER_FITTING_REPORT_FORMAT",
    "PUTTER_HEAD_FORMAT",
    "PutterHeadDocument",
    "PutterHeadProvenance",
    "PutterCounterfactual",
    "PutterFittingReport",
    "PutterStrikeResult",
    "PutterTwist",
    "PuttingOutcome",
    "compare_putter_counterfactuals",
    "putter_fitting_report_to_json",
    "scenario_for_head",
    "head_moi_for_strike",
    "putter_head_from_json",
    "putter_head_from_library",
    "putter_head_from_mesh",
    "putter_head_from_stl",
    "putter_head_to_json",
    "putter_spec",
    "strike_with_head",
    "twist_response",
    "scale_shaft_profile",
    "shaft_component_mass_properties",
    "shaft_profile_from_csv",
    "shaft_profile_from_json",
    "shaft_profile_from_json_dict",
    "shaft_profile_to_csv",
    "shaft_profile_to_json",
    "shaft_profile_to_json_dict",
    "GripKinematics",
    "ShaftDeliveryDeltas",
    "ShaftTipMass",
    "solve_shaft_delivery",
    "solve_shaft_bending_modes",
    "solve_cantilever_tip_response",
    "simulate_reduced_turf_contact",
    "run_turf_convergence_study",
    "turf_profile_from_json",
    "turf_profile_from_json_dict",
    "turf_profile_preset",
    "turf_profile_to_json",
    "turf_profile_to_json_dict",
    "turf_profiles_for_variation_plan",
    "wedge_preset",
    "wedge_body_profile_m",
    "wedge_contact_candidates",
    "wedge_face_contact_point_m",
    "wedge_ground_clearance_to_json_dict",
    "wedge_parameters_from_json",
    "wedge_parameters_to_json",
]
