"""Canonical ownership and headless import contracts for standalone Sidekick."""

from __future__ import annotations

import ast
import os
import subprocess  # nosec B404 - fixed interpreter and local import probes
import sys
from pathlib import Path

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.headless_safe]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_CANONICAL_SIDEKICK = _REPO_ROOT / "src" / "shared" / "python" / "sidekick"
_CHILD_COPY_HEADER = "# WARNING: DO NOT EDIT THIS FILE DIRECTLY."
_STANDALONE_SOURCES = (
    "__main__.py",
    "persistence/__init__.py",
    "persistence/schema.py",
    "persistence/state_profile.py",
    "standalone/__init__.py",
    "standalone/onboarding.py",
    "standalone/preferences.py",
    "standalone/runner.py",
    "standalone/session_store.py",
    "standalone/window.py",
)
_REQUIRED_PUBLIC_API = {
    "__main__.py": {
        "SidekickArgumentParser",
        "build_parser",
        "launch_gui",
        "main",
        "parse_cli_args",
        "run_headless",
    },
    "persistence/schema.py": {
        "PROFILE_SCHEMA_VERSION",
        "PROFILE_SCHEMA_VERSION_KEY",
        "ProfilePayload",
    },
}


def _canonical_import_environment() -> dict[str, str]:
    """Return an isolated environment that imports only this Tools checkout."""
    env = os.environ.copy()
    env["PYTHONNOUSERSITE"] = "1"
    pythonpath_parts = [
        str(_REPO_ROOT / "src"),
        str(_REPO_ROOT / "src" / "python" / "src"),
    ]
    import site

    user_site = site.getusersitepackages()
    if isinstance(user_site, str) and os.path.isdir(user_site):
        pythonpath_parts.append(user_site)
    for p in site.getsitepackages():
        if os.path.isdir(p):
            pythonpath_parts.append(p)
    env["PYTHONPATH"] = os.pathsep.join(pythonpath_parts)
    return env


def test_standalone_sources_are_canonical_parent_files() -> None:
    """Every migrated source must exist without a downstream warning header."""
    for relative in _STANDALONE_SOURCES:
        source = _CANONICAL_SIDEKICK / relative
        assert source.is_file(), f"missing canonical standalone source: {relative}"
        first_line = source.read_text(encoding="utf-8").partition("\n")[0]
        assert first_line != _CHILD_COPY_HEADER


def test_standalone_sources_declare_explicit_public_api() -> None:
    """Every canonical Sidekick module must define its stable public surface."""
    for relative in _STANDALONE_SOURCES:
        source = _CANONICAL_SIDEKICK / relative
        tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
        declaration = next(
            (
                node
                for node in tree.body
                if isinstance(node, ast.Assign)
                and any(
                    isinstance(target, ast.Name) and target.id == "__all__"
                    for target in node.targets
                )
            ),
            None,
        )
        assert declaration is not None, f"{relative} must define explicit __all__"
        assert isinstance(declaration.value, (ast.List, ast.Tuple))
        exports = {
            ast.literal_eval(element)
            for element in declaration.value.elts
            if isinstance(element, ast.Constant)
        }
        assert _REQUIRED_PUBLIC_API.get(relative, set()).issubset(exports)


def test_standalone_sources_respect_repository_line_budget() -> None:
    """New canonical modules must stay within the repository's 400-line limit."""
    for relative in _STANDALONE_SOURCES:
        source = _CANONICAL_SIDEKICK / relative
        line_count = len(source.read_text(encoding="utf-8").splitlines())
        assert line_count <= 400, f"{relative} has {line_count} lines (maximum: 400)"


def test_standalone_core_imports_without_qt(tmp_path: Path) -> None:
    """CLI parsing and headless dispatch modules must not initialize Qt."""
    script = """
import importlib
import pathlib
import sys

module_names = (
    "shared.python.sidekick.__main__",
    "sidekick.standalone",
    "sidekick.standalone.onboarding",
    "sidekick.standalone.preferences",
    "sidekick.standalone.runner",
    "sidekick.persistence",
    "sidekick.persistence.schema",
    "sidekick.persistence.state_profile",
    "sidekick.standalone.session_store",
)
modules = [importlib.import_module(name) for name in module_names]
canonical_root = pathlib.Path(sys.argv[1]).resolve()
for module in modules:
    assert pathlib.Path(module.__file__).resolve().is_relative_to(canonical_root)
assert not any(name == "PyQt6" or name.startswith("PyQt6.") for name in sys.modules)
"""
    result = subprocess.run(  # nosec B603 - fixed interpreter and local script
        [sys.executable, "-c", script, str(_CANONICAL_SIDEKICK)],
        cwd=tmp_path,
        env=_canonical_import_environment(),
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, result.stderr


def test_standalone_profile_round_trip_uses_canonical_schema(tmp_path: Path) -> None:
    """Standalone profiles must preserve payloads through the parent-owned store."""
    script = """
import json
import pathlib
import sys

from sidekick.persistence.schema import ProfilePayload
from sidekick.standalone.session_store import StandaloneSessionStore

root = pathlib.Path(sys.argv[1])
store = StandaloneSessionStore(root)
payload = ProfilePayload(data={"profile": "chat-first", "theme_name": "solarized"})
store.save_profile("primary", payload)
loaded = store.load_profile("primary")
assert loaded == payload
assert store.list_profiles() == ["primary"]
store.set_last_profile("primary")
assert store.last_profile() == "primary"
print(json.dumps(loaded.to_dict(), sort_keys=True))
"""
    result = subprocess.run(  # nosec B603 - fixed interpreter and local script
        [sys.executable, "-c", script, str(tmp_path / "profiles")],
        cwd=tmp_path,
        env=_canonical_import_environment(),
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, result.stderr
    assert '"profile": "chat-first"' in result.stdout


def test_python_m_sidekick_help_uses_canonical_cli(tmp_path: Path) -> None:
    """The compatibility command must execute the parent-owned CLI entry point."""
    result = subprocess.run(  # nosec B603 - fixed interpreter and module
        [sys.executable, "-m", "sidekick", "--help"],
        cwd=tmp_path,
        env=_canonical_import_environment(),
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode == 0, result.stderr
    assert "Standalone Sidekick launcher and headless dispatcher." in result.stdout
    assert "{gui,run}" in result.stdout
