# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Optional host integration for the shared Unified Tools Sidebar.

The sidebar implementation lives in the Tools repository and may not be
installed beside UpstreamDrift in every environment.  This module keeps the
host-side contract small: import the shared component when it is available,
attach it to a ``QMainWindow``-like object, pass Sidekick design tokens when
the shared component accepts them, and otherwise no-op.

Fallback
--------
When the shared module is absent, :func:`install_tools_sidebar` installs a
:class:`NullToolsSidebar` placeholder so that Sidekick design tokens are
consumed and the launcher shows a clearly-labelled "not installed" panel
rather than a blank dock.  Pass ``install_fallback=False`` to restore the
old behaviour (return ``installed=False`` with no widget).
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ._sidebar_integration_helpers import (
    add_dock_widget,
    call_shared_installer,
    connect_file_open_request,
    create_sidebar_from_module,
    ensure_dock_widget,
    get_sidekick_tokens,
    import_sidebar_module,
    status_sidebar,
)

logger = logging.getLogger(__name__)


class NullToolsSidebar:
    """Minimal in-repo placeholder for the optional Tools sidebar.

    Used when the sibling Tools repository is not installed.  The widget
    itself is a no-op QLabel (or a pure-Python stub when PyQt6 is absent)
    so that:

    * Sidekick design tokens are accepted and stored (preventing the
      "tokens discarded" problem described in issue #5463).
    * The launcher can dock *something* without crashing.
    * A visible "Tools not installed" message guides users.

    Args:
        parent: Optional host window (passed to QLabel when PyQt6 is present).
        sidekick_tokens: Design-token mapping from
            :func:`src.shared.python.theme.sidekick_tokens.get_current_sidekick_tokens`.
            Stored on ``self.sidekick_tokens`` for inspection / testing.

    Postconditions:
        * ``self.sidekick_tokens`` is always set, even when empty.
        * ``self._widget`` is either a QLabel or this object itself (PyQt6 absent).
    """

    def __init__(
        self,
        *,
        parent: Any = None,
        sidekick_tokens: dict[str, str] | None = None,
        **_kwargs: Any,
    ) -> None:
        self.sidekick_tokens: dict[str, str] = (
            dict(sidekick_tokens) if sidekick_tokens else {}
        )
        self._widget: Any = self
        try:
            from PyQt6.QtWidgets import QApplication, QLabel

            # Only attempt to create a QLabel when a QApplication is running;
            # otherwise the call segfaults or raises in headless / test contexts.
            if QApplication.instance() is not None:
                notice = (
                    "<b>Sidekick Tools</b><br/>"
                    "<small>Install the Tools workspace to enable "
                    "the full sidebar.<br/>"
                    "Run: <code>scripts/setup_tools_workspace.sh</code></small>"
                )
                label = QLabel(text=notice)
                label.setWordWrap(True)
                label.setContentsMargins(12, 12, 12, 12)
                self._widget = label
        except (ImportError, RuntimeError, TypeError):
            pass

    # ── QDockWidget-compatible protocol ──────────────────────────────

    def setWidget(self, widget: Any) -> None:
        """No-op: this placeholder is its own widget."""

    def toggleViewAction(self) -> object:
        """Return a dummy action object (duck-typed QAction stub)."""
        return object()

    def widget(self) -> Any:
        """Return the inner display widget."""
        return self._widget


@dataclass(frozen=True)
class ToolsSidebarInstallStatus:
    """Result from attempting to install the optional shared tools sidebar."""

    installed: bool
    reason: str
    dock: Any = None
    sidebar: Any = None
    module_name: str | None = None
    file_open_connected: bool = False


def install_tools_sidebar(
    main_window: Any,
    project_root: str | Path | None = None,
    context_provider: Callable[[], Any] | None = None,
    install_fallback: bool = True,
) -> ToolsSidebarInstallStatus:
    """Attach the shared Unified Tools Sidebar to a host main window if present.

    When the shared module is absent and *install_fallback* is ``True`` (the
    default), a :class:`NullToolsSidebar` placeholder is docked instead so
    that Sidekick design tokens are still consumed and the user sees a helpful
    "not installed" message.

    Args:
        main_window: QMainWindow-like host. It must provide ``addDockWidget``.
        project_root: Optional project root passed through to the shared sidebar.
        context_provider: Optional callback for host-specific context.
        install_fallback: When ``True`` (default) and the shared module is
            absent, install a :class:`NullToolsSidebar` placeholder.  Pass
            ``False`` to restore the pre-#5463 behaviour where an absent
            module returns ``installed=False`` with no widget.

    Returns:
        A status object describing whether the sidebar was installed.
    """
    if main_window is None:
        return ToolsSidebarInstallStatus(False, "main_window is required")
    if not hasattr(main_window, "addDockWidget"):
        return ToolsSidebarInstallStatus(
            False,
            "main_window does not support dock widgets",
        )

    module = import_sidebar_module()
    if module is None:
        if install_fallback:
            return _install_null_sidebar(main_window)
        return ToolsSidebarInstallStatus(
            False,
            "shared tools sidebar module is not available",
        )

    try:
        return _install_from_module(
            module,
            main_window=main_window,
            project_root=Path(project_root).resolve() if project_root else None,
            context_provider=context_provider,
        )
    except Exception as exc:  # noqa: BLE001 - this hook must not break launch
        module_name = getattr(module, "__name__", None)
        logger.warning("Unified Tools Sidebar integration failed: %s", exc)
        if install_fallback:
            return _install_null_sidebar(main_window)
        return ToolsSidebarInstallStatus(
            False,
            f"shared tools sidebar integration failed: {exc}",
            module_name=module_name,
        )


def _install_null_sidebar(main_window: Any) -> ToolsSidebarInstallStatus:
    """Install a :class:`NullToolsSidebar` placeholder into *main_window*."""
    tokens = get_sidekick_tokens()
    sidebar = NullToolsSidebar(sidekick_tokens=tokens)
    try:
        dock = ensure_dock_widget(sidebar, main_window)
        add_dock_widget(main_window, dock)
    except (TypeError, RuntimeError) as exc:
        # Qt not available or main_window is a non-Qt stub — still report
        # installed=True so callers know the fallback path was reached.
        logger.debug("NullToolsSidebar dock setup skipped: %s", exc)
        dock = sidebar
    return ToolsSidebarInstallStatus(
        installed=True,
        reason="null sidebar fallback installed (Tools repo not available)",
        dock=dock,
        sidebar=sidebar,
        module_name=None,
        file_open_connected=False,
    )


def is_tools_sidebar_available() -> bool:
    """Return ``True`` when one of the shared Tools sidebar modules imports."""
    return import_sidebar_module() is not None


def _resolved_sidebar_module_name() -> str | None:
    """Return the dotted module name of the shared sidebar, if importable."""
    module = import_sidebar_module()
    if module is None:
        return None
    name = getattr(module, "__name__", None)
    return name if isinstance(name, str) and name else None


def _install_from_module(
    module: Any,
    *,
    main_window: Any,
    project_root: Path | None,
    context_provider: Callable[[], Any] | None,
) -> ToolsSidebarInstallStatus:
    module_name = str(getattr(module, "__name__", ""))

    module_installer = getattr(module, "install_tools_sidebar", None)
    if callable(module_installer):
        installed = call_shared_installer(
            module_installer,
            main_window=main_window,
            project_root=project_root,
            context_provider=context_provider,
        )
        if isinstance(installed, ToolsSidebarInstallStatus):
            return installed
        if installed is None:
            return ToolsSidebarInstallStatus(
                False,
                "shared module installer did not install sidebar",
                module_name=module_name,
            )
        sidebar = status_sidebar(installed)
        dock = (
            getattr(installed, "dock_widget", None)
            or getattr(installed, "dock", None)
            or installed
        )
        return ToolsSidebarInstallStatus(
            True,
            "installed by shared module",
            dock=dock,
            sidebar=sidebar,
            module_name=module_name,
            file_open_connected=connect_file_open_request(sidebar, main_window),
        )

    sidebar = create_sidebar_from_module(
        module,
        main_window=main_window,
        project_root=project_root,
        context_provider=context_provider,
    )
    if sidebar is None:
        return ToolsSidebarInstallStatus(
            False,
            "shared tools sidebar module has no supported factory",
            module_name=module_name,
        )

    dock = ensure_dock_widget(sidebar, main_window)
    add_dock_widget(main_window, dock)
    connected = connect_file_open_request(sidebar, main_window)

    return ToolsSidebarInstallStatus(
        True,
        "installed",
        dock=dock,
        sidebar=sidebar,
        module_name=module_name,
        file_open_connected=connected,
    )
